In [27]:
# Question 1

class Employee:
    # COUNT THE NUMBER OF EMPLOYEES
    empCount = 0

    # CONSTRUCTOR TO INITIALIZE NAME, FAMILY, SALARY, DEPARTMENT
    def __init__(self, name, family, salary, department):
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department
        Employee.empCount += 1    # EMPLOYEE COUNT

    # TO DISPLAY DETAILS OF EMPLOYEE
    def display(self):
        print('Employee Name:', self.name)
        print('Family Members:', self.family)
        print('Employee Annual Salary:', self.salary)
        print('Department:', self.department)
        print("---------")

    # FUNCTION FOR AVERAGE SALARY OF EMPLOYEE
    def avg_salary(self):
        total_salary = 0
        total_salary += float(self.salary)
        avg = total_salary / Employee.empCount
        print('Average salary of the Employee:', avg)

# INHERITING - EMPLOYEE CLASS
class Fulltime_Employee(Employee):
    def __init__(self, name, family, salary, department, emp_type):
        Employee.__init__(self, name, family, salary, department)
        self.emp_type = emp_type

    #FUNCTION TO DISPLAY EMPLOYEE DETAILS
    def display(self):
        print("Employee Name :", self.name)
        print('Family Members:', self.family)
        print('Employee Annual Salary:', self.salary)
        print('Department:', self.department)
        print('Type of Employment :', self.emp_type)
        print("---------")
# INSTANCES FOR Fulltime EMPLOYEE CLASS
emp1 = Fulltime_Employee('Manisha', '3', '700100', 'Application Developer', 'Fulltime')
emp2 = Fulltime_Employee('Mounika', '5', '518000', 'System Analyst', 'Fulltime')
# INSTANCES FOR EMPLOYEE CLASS
emp3 = Employee('Sirisha', '4', '604000', 'Web Developer')
emp4 = Employee('Hari', '5', '714000', 'Saleforce Developer')

print("Count of the Employees :", emp1.empCount)
emp1.avg_salary()
emp1.display()
emp2.display()
emp3.display()
emp4.display()


Count of the Employees : 4
Average salary of the Employee: 175025.0
Employee Name : Manisha
Family Members: 3
Employee Annual Salary: 700100
Department: Application Developer
Type of Employment : Fulltime
---------
Employee Name : Mounika
Family Members: 5
Employee Annual Salary: 518000
Department: System Analyst
Type of Employment : Fulltime
---------
Employee Name: Sirisha
Family Members: 4
Employee Annual Salary: 604000
Department: Web Developer
---------
Employee Name: Hari
Family Members: 5
Employee Annual Salary: 714000
Department: Saleforce Developer
---------


In [28]:
# Question 2


import numpy as np

# creating array of size 20
random_vector = np.random.uniform(1, 20, 20)
print("Random Vector : \n", random_vector)

# reshape the array to 4 by 5
random_vector = random_vector.reshape(4,5)
print("after reshaping (4 by 5): \n", random_vector)

# replace the max in each row
random_vector[np.arange(len(random_vector)), random_vector.argmax(1)] = 0
print("Replacing the max in each row : \n", random_vector)



Random Vector : 
 [10.0196552  10.22102599 18.4420317   9.67070938  8.5183484   5.10795588
  1.41919186 19.92540391  5.58782076  4.29542361  5.87639177 12.98184416
 18.8703152  16.01307509  4.12773584 17.66968337 15.98961389  2.09419916
 15.37582826  4.96511525]
after reshaping (4 by 5): 
 [[10.0196552  10.22102599 18.4420317   9.67070938  8.5183484 ]
 [ 5.10795588  1.41919186 19.92540391  5.58782076  4.29542361]
 [ 5.87639177 12.98184416 18.8703152  16.01307509  4.12773584]
 [17.66968337 15.98961389  2.09419916 15.37582826  4.96511525]]
Replacing the max in each row : 
 [[10.0196552  10.22102599  0.          9.67070938  8.5183484 ]
 [ 5.10795588  1.41919186  0.          5.58782076  4.29542361]
 [ 5.87639177 12.98184416  0.         16.01307509  4.12773584]
 [ 0.         15.98961389  2.09419916 15.37582826  4.96511525]]
